spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/whenwheredb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  logging:
    level:
      me.silvernine: DEBUG
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400